# Generated by Django 4.0.5 on 2022-06-19 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['pk'], 'verbose_name': 'Преподователь', 'verbose_name_plural': 'Преподователи'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='total_points',
            field=models.FloatField(default=0, verbose_name='Общее количество баллов'),
        ),
    ]
