# Generated by Django 4.0.5 on 2022-06-22 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование')),
                ('point', models.FloatField(verbose_name='Балл')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': '4. Категории',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent_min', models.IntegerField(verbose_name='Минимальный процент')),
                ('percent_max', models.IntegerField(verbose_name='Максимальный процент')),
            ],
            options={
                'verbose_name': 'Условие 1',
                'verbose_name_plural': '5.1 Условия',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Condition3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_min', models.IntegerField(verbose_name='Минимальное количество')),
                ('amount_max', models.IntegerField(verbose_name='Максимальное количество')),
            ],
            options={
                'verbose_name': 'Условие 3',
                'verbose_name_plural': '5.3 Условия',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Критерий оценки эффективности деятельности',
                'verbose_name_plural': '2. Критерии оценки эффективности деятельности',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=250, verbose_name='Наименование')),
                ('category', models.ManyToManyField(to='kpi.category', verbose_name='Категории')),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kpi.criteria', verbose_name='Критерий оценки эффективности деятельности')),
            ],
            options={
                'verbose_name': 'Количественный, качественный или объёмный показатель',
                'verbose_name_plural': '3. Количественные, качественные или объёмные показатели',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Kpi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=250, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Показатель эффективности деятельности',
                'verbose_name_plural': '1. Показатели эффективности деятельности',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.FloatField(blank=True, null=True, verbose_name='Балл за количественный, качественный или объёмный показатель')),
                ('text', models.TextField(blank=True, max_length=1700)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kpi.indicator', verbose_name='Показатель')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Ответ преподователя',
                'verbose_name_plural': '6. Ответы преподователей',
                'ordering': ['user'],
            },
        ),
        migrations.AddField(
            model_name='criteria',
            name='kpi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kpi.kpi', verbose_name='Показатель эффективности деятельности'),
        ),
        migrations.AddField(
            model_name='category',
            name='condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kpi.condition'),
        ),
        migrations.AddField(
            model_name='category',
            name='condition3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kpi.condition3'),
        ),
    ]
